#!/usr/bin/env php
<?php

use BAS\zf2\ConsoleCommands,
    Symfony\Component\Console\Application;

if(file_exists(__DIR__ . '/vendor/autoload.php')){
    require_once __DIR__ . '/vendor/autoload.php';
} else {
    die('Run `php composer.phar install` to get project dependencies');
}

$commands = new ConsoleCommands();
$application = new Application();
$application->addCommands($commands->getCommands());
$application->run();
